#!/usr/bin/env node
// tests/security/regression.mjs
// v2.14.0 — Defense in Depth, Layer 3: RECOVER
// Per ADR 0003: Regression test for injection counters.
// Runs canary corpus against defense library, asserts coverage >= 95% on block/warn.

import { readFileSync, existsSync, writeFileSync, mkdirSync } from 'node:fs';
import { resolve, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const REPO_ROOT = resolve(__dirname, '../..');

const corpusPath = resolve(REPO_ROOT, 'security/defense/patterns/canary-corpus.v1.json');
const baselinePath = resolve(__dirname, 'baseline.json');

if (!existsSync(corpusPath)) {
  console.error(`FAIL: corpus not found at ${corpusPath}`);
  process.exit(1);
}

const corpus = JSON.parse(readFileSync(corpusPath, 'utf8'));
const counters = await import(resolve(REPO_ROOT, 'security/defense/injection-counters.mjs'));

const results = {
  total: corpus.payloads.length,
  byExpected: { block: 0, warn: 0, allow: 0 },
  flagged: 0,
  missed: 0,
  falsePositive: 0,
  trueNegative: 0,
  coverage: 0,
  perPayload: []
};

for (const p of corpus.payloads) {
  results.byExpected[p.expected_action]++;
  const detection = counters.detectInjection(p.content);
  const wasFlagged = detection.detected;

  let verdict;
  if (p.expected_action === 'allow') {
    // Should NOT be flagged
    if (wasFlagged) {
      verdict = 'false-positive';
      results.falsePositive++;
    } else {
      verdict = 'true-negative';
      results.trueNegative++;
    }
  } else {
    // Should be flagged (block or warn)
    if (wasFlagged) {
      verdict = 'true-positive';
      results.flagged++;
    } else {
      verdict = 'false-negative';
      results.missed++;
    }
  }
  results.perPayload.push({
    id: p.id,
    category: p.category,
    expected: p.expected_action,
    flagged: wasFlagged,
    verdict,
    threats: detection.threats.map(t => t.id)
  });
}

const detectablePayloads = results.byExpected.block + results.byExpected.warn;
results.coverage = detectablePayloads > 0
  ? ((results.flagged / detectablePayloads) * 100).toFixed(2)
  : 0;

const falsePositiveRate = results.byExpected.allow > 0
  ? ((results.falsePositive / results.byExpected.allow) * 100).toFixed(2)
  : 0;

console.log(`
=== Security Regression Report (v2.14.0) ===`);
console.log(`Total payloads: ${results.total}`);
console.log(`  Block expected:  ${results.byExpected.block}`);
console.log(`  Warn expected:   ${results.byExpected.warn}`);
console.log(`  Allow expected:  ${results.byExpected.allow}`);
console.log(`
Results:`);
console.log(`  True positive:   ${results.flagged} (correctly flagged)`);
console.log(`  False negative:  ${results.missed} (missed attack)`);
console.log(`  True negative:   ${results.trueNegative} (correctly skipped)`);
console.log(`  False positive:  ${results.falsePositive} (flagged safe content)`);
console.log(`
Metrics:`);
console.log(`  Detection coverage: ${results.coverage}%  (target >= 95%)`);
console.log(`  False positive rate: ${falsePositiveRate}%  (target < 2%)`);

// Compare to baseline
let baseline = null;
if (existsSync(baselinePath)) {
  baseline = JSON.parse(readFileSync(baselinePath, 'utf8'));
  console.log(`
Baseline (from ${baselinePath}):`);
  console.log(`  Coverage: ${baseline.coverage}%`);
  if (parseFloat(results.coverage) < parseFloat(baseline.coverage)) {
    console.error(`
❌ FAIL: Coverage regressed from ${baseline.coverage}% to ${results.coverage}%`);
    process.exit(1);
  }
}

// Update baseline if coverage improved
if (!baseline || parseFloat(results.coverage) > parseFloat(baseline.coverage)) {
  const newBaseline = {
    updated: new Date().toISOString(),
    coverage: results.coverage,
    falsePositiveRate,
    flagged: results.flagged,
    missed: results.missed,
    falsePositive: results.falsePositive,
    total: results.total
  };
  writeFileSync(baselinePath, JSON.stringify(newBaseline, null, 2));
  console.log(`
✅ Baseline updated: ${results.coverage}% coverage`);
}

// Write human-readable report
mkdirSync(resolve(REPO_ROOT, 'docs/security'), { recursive: true });
const reportPath = resolve(REPO_ROOT, 'docs/security/regression-report.md');
const reportMd = `# Security Regression Report

> Auto-generated by \`tests/security/regression.mjs\` on ${new Date().toISOString()}

## Summary

| Metric | Value | Target |
|--------|-------|--------|
| Total payloads | ${results.total} | — |
| True positives | ${results.flagged} | — |
| False negatives | ${results.missed} | 0 |
| True negatives | ${results.trueNegative} | — |
| False positives | ${results.falsePositive} | <2% of allow |
| **Detection coverage** | **${results.coverage}%** | **≥95%** |
| **False positive rate** | **${falsePositiveRate}%** | **<2%** |

## Per-Payload Results

| ID | Category | Expected | Flagged | Verdict | Threats |
|----|----------|----------|---------|---------|---------|
${results.perPayload.map(p => `| ${p.id} | ${p.category} | ${p.expected} | ${p.flagged} | ${p.verdict} | ${p.threats.join(', ') || '—'} |`).join('\n')}

## Last Run

- **When:** ${new Date().toISOString()}
- **Canary corpus version:** v${corpus.version}
- **Corpus size:** ${corpus.payloads.length} payloads

## How to Read This Report

- **True positive** = attack payload correctly flagged (good)
- **False negative** = attack payload NOT flagged (bad — defense gap)
- **True negative** = safe content correctly NOT flagged (good)
- **False positive** = safe content incorrectly flagged (bad — UX issue)

If coverage drops below 95% or false positive rate exceeds 2%, gate fails. Review patterns in \`security/defense/injection-counters.mjs\` and add new patterns to address gaps.
`;

writeFileSync(reportPath, reportMd);
console.log(`
Report written to: ${reportPath}`);

// Final verdict
if (parseFloat(results.coverage) >= 95 && parseFloat(falsePositiveRate) < 2) {
  console.log(`
✅ PASS: ${results.coverage}% coverage, ${falsePositiveRate}% false positive rate`);
  process.exit(0);
} else if (parseFloat(results.coverage) >= 90) {
  console.log(`
⚠️  WARN: Coverage ${results.coverage}% below 95% target, but above 90% floor`);
  process.exit(0);
} else {
  console.error(`
❌ FAIL: Coverage ${results.coverage}% below 90% floor`);
  process.exit(1);
}
